import Link from "next/link";
import { notFound } from "next/navigation";
import { analyse, monthLabel } from "@/lib/analysis";
import { explainFinding } from "@/lib/explain";
import { readStore, saveExplanation } from "@/lib/store";
import { fmtAed, scenarioSaving } from "@/lib/tariff";
import type { Explanation } from "@/lib/types";

export const dynamic = "force-dynamic";

function Sheet({ lang, e, siteName, month, scenario, evidence, hint }: {
  lang: "en" | "ar";
  e: Explanation;
  siteName: string;
  month: string;
  scenario: { reductionKwh: number; monthlySaving: number; annualSaving: number } | null;
  evidence: string[];
  hint: string;
}) {
  const ar = lang === "ar";
  const t = ar
    ? { title: "مهمة لمدير المرافق", site: "الموقع", month: "الشهر", actions: "الإجراءات", owner: "المسؤول", effort: "الجهد", scenario: "سيناريو التوفير", scenarioNote: "سيناريو وليس توفيرًا مضمونًا — وفق تعرفة ديوا شاملة رسم الوقود والضريبة", monthly: "شهريًا", annual: "سنويًا", evidence: "الفواتير المرجعية", signoff: "تم بواسطة / التاريخ", generated: "أُنشئ بواسطة WattWatch" }
    : { title: "Task sheet for the facilities manager", site: "Site", month: "Month", actions: "Actions", owner: "Owner", effort: "Effort", scenario: "Savings scenario", scenarioNote: "Scenario, not a guaranteed saving — DEWA slab tariff incl. fuel surcharge and VAT", monthly: "per month", annual: "per year", evidence: "Evidence bills", signoff: "Completed by / date", generated: "Generated by WattWatch" };
  return (
    <section dir={ar ? "rtl" : "ltr"} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6 print:break-after-page print:border-0 print:shadow-none">
      <div className="text-xs uppercase tracking-wide text-slate-500">{t.title}</div>
      <h1 className="mt-1 text-xl font-semibold">{ar ? e.headline_ar : e.headline_en}</h1>
      <div className="mt-2 flex flex-wrap gap-x-6 gap-y-1 text-sm text-slate-600">
        <span>
          {t.site}: <b>{siteName}</b>
        </span>
        <span>
          {t.month}: <b>{month}</b>
        </span>
      </div>
      <p className="mt-4 text-slate-800">{ar ? e.explanation_ar : e.explanation_en}</p>
      <p className="mt-1 text-sm text-slate-600">{hint}</p>

      <h2 className="mt-5 font-semibold">{t.actions}</h2>
      <table className="mt-2 w-full text-sm">
        <thead className="text-start text-xs uppercase text-slate-500">
          <tr>
            <th className="w-8 py-1"></th>
            <th className="py-1 text-start">{t.actions}</th>
            <th className="text-start">{t.owner}</th>
            <th className="text-start">{t.effort}</th>
          </tr>
        </thead>
        <tbody>
          {e.actions.map((a, i) => (
            <tr key={i} className="border-t border-slate-200 align-top">
              <td className="py-2">
                <span className="inline-block h-4 w-4 rounded border border-slate-400" />
              </td>
              <td className="py-2">
                <div className="font-medium">{ar ? a.title_ar : a.title_en}</div>
                <ul className="mt-1 list-disc ps-5 text-slate-700">
                  {(ar ? a.checks_ar : a.checks_en).map((c, j) => (
                    <li key={j}>{c}</li>
                  ))}
                </ul>
              </td>
              <td className="py-2">{a.owner}</td>
              <td className="py-2">{a.effort}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {scenario && (
        <div className="mt-5 rounded-md bg-emerald-50 p-3">
          <div className="font-semibold text-emerald-800">{t.scenario}</div>
          <div className="mt-1 text-sm text-emerald-900" dir="ltr">
            −{scenario.reductionKwh.toLocaleString()} kWh → <b>{fmtAed(scenario.monthlySaving)}</b> {t.monthly} · <b>{fmtAed(scenario.annualSaving)}</b> {t.annual}
          </div>
          <div className="mt-1 text-xs text-emerald-700">{t.scenarioNote}</div>
        </div>
      )}

      <div className="mt-5 text-xs text-slate-500">
        {t.evidence}: <span dir="ltr">{evidence.join(" · ")}</span>
      </div>
      <div className="mt-6 flex justify-between border-t border-slate-200 pt-3 text-xs text-slate-500">
        <span>{t.signoff}: ____________________</span>
        <span>
          {t.generated} · {e.model}
        </span>
      </div>
    </section>
  );
}

export default async function SheetPage({ params }: PageProps<"/findings/[id]/sheet">) {
  const { id } = await params;
  const findingId = decodeURIComponent(id);
  const store = readStore();
  const f = analyse(store.sites, store.bills, store.settings).find((x) => x.id === findingId);
  if (!f) notFound();
  const site = store.sites.find((s) => s.id === f.siteId);
  if (!site) notFound();
  let e = store.explanations[f.id];
  if (!e) {
    e = await explainFinding(f, site);
    saveExplanation(e);
  }
  const evidence = f.evidenceBillIds.map((bid) => store.bills.find((b) => b.id === bid)).filter((b) => b !== undefined);
  const focus = evidence[0];
  const scenario = f.severity !== "data-quality" && focus && f.excessKwh > 0
    ? scenarioSaving(focus.kwh, f.excessKwh, store.settings.tariff, site.premisesType, focus.fuelSurchargeRate, focus.meterCharge)
    : null;
  const evidenceLabels = evidence.map((b) => `${monthLabel(b.billMonth)} — ${b.kwh.toLocaleString()} kWh, ${fmtAed(b.totalAed)}`);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 print:hidden">
        <Link href={`/findings/${encodeURIComponent(f.id)}`} className="text-sm text-slate-500 hover:underline">
          ← Back to finding
        </Link>
        <span className="text-sm text-slate-500">One page in English, one in Arabic. Use your browser&apos;s print dialog to save as PDF.</span>
      </div>
      <Sheet lang="en" e={e} siteName={site.name} month={monthLabel(f.billMonth)} scenario={scenario} evidence={evidenceLabels} hint={e.explanation_en.includes(f.whyHint) ? "" : f.whyHint} />
      <Sheet lang="ar" e={e} siteName={site.nameAr ?? site.name} month={monthLabel(f.billMonth)} scenario={scenario} evidence={evidenceLabels} hint="" />
    </div>
  );
}
